import { NextResponse } from 'next/server'
import fs from 'fs'
import path from 'path'

/**
 * API route to serve Mediterranean plants dataset
 * This reads the JSON file generated by the download_dataset.py script
 */
export async function GET() {
  try {
    const filePath = path.join(process.cwd(), 'lib', 'mediterranean_plants_data.json')
    
    if (!fs.existsSync(filePath)) {
      // Return empty dataset if file doesn't exist yet
      // User needs to run the download script first
      return NextResponse.json({
        plants: [],
        total_plants: 0,
        message: 'Dataset not found. Please run: python scripts/download_dataset.py'
      })
    }
    
    const fileContent = fs.readFileSync(filePath, 'utf-8')
    const data = JSON.parse(fileContent)
    
    return NextResponse.json(data)
  } catch (error) {
    console.error('Error loading Mediterranean plants dataset:', error)
    return NextResponse.json(
      {
        plants: [],
        total_plants: 0,
        error: 'Failed to load dataset'
      },
      { status: 500 }
    )
  }
}

